### ISSUE TITLE
Lightbend subscription

### ISSUE THREAD

**Issue by xpavlic4** [typesafehub/ReactiveMaps#51]
I cannot even open the project in Intellij IDEA, it needs some kind of subscription, so I went to your website and there is only "Contact Sales" for the subscription. I just want to try it out, is there a way to achieve it?

**Comment by noelmcloughlin** [comment]
I got this error. I followed the url but not sure how to get a trial subscription id.
```
[error] == Typesafe Reactive Platform: project/typesafe.properties must exist with typesafe.subscription=<YOUR SUBSCRIPTION ID>.
[error] == Visit http://typesafe.com/account/id to obtain a trial subscription id.
[error] Use 'last' for the full log.
```

**Comment by raboof** [comment]
I'm sorry about the confusion.

The bad news is: this example is outdated and probably not useful anymore.

The good news is: the components that required a Lightbend Subscription have now been replaced with ones that are fully open source, so you no longer have to start a trial!

I'll make sure this repository gets properly archived and no longer shown at https://developer.lightbend.com
